from __future__ import annotations

import argparse
import json
import logging
import subprocess
import sys
from pathlib import Path
from typing import Any

from db.setup_db import DB_PATH, setup_database
from graph import insight_graph
from llm import OpenRouterSettings, model_session


def run(question: str, db_path: str | None = None, *, model_settings: OpenRouterSettings | None = None) -> dict:
    path = Path(db_path) if db_path else setup_database()
    initial_state = {"question": question, "db_path": str(path), "queries": [], "results": [], "insights": [], "chart_specs": [], "errors": []}
    with model_session(model_settings):
        return dict(insight_graph.invoke(initial_state, config={"recursion_limit": 64}))


def _json_default(value: Any) -> Any:
    """Persist a Plotly figure generated by chart tools for the dashboard."""
    if hasattr(value, "to_plotly_json"):
        return value.to_plotly_json()
    return str(value)


def main() -> None:
    parser = argparse.ArgumentParser(description="InsightPilot autonomous SQLite analyst")
    parser.add_argument("question", help="Natural-language business question")
    parser.add_argument("--db", help="Path to an existing SQLite database")
    parser.add_argument("--dashboard", action="store_true", help="Launch Streamlit using this result")
    args = parser.parse_args()
    result = run(args.question, args.db)
    output_path = Path("dashboard") / "latest_run.json"
    output_path.parent.mkdir(exist_ok=True)
    output_path.write_text(json.dumps(result, indent=2, default=_json_default), encoding="utf-8")
    print(json.dumps(result, indent=2, default=_json_default))
    if args.dashboard:
        subprocess.run([sys.executable, "-m", "streamlit", "run", "dashboard/app.py"], check=False)


if __name__ == "__main__":
    logging.basicConfig(level=logging.INFO, format="%(levelname)s %(name)s: %(message)s")
    main()
